### ISSUE TITLE
suggestion export likes to file

### ISSUE THREAD

**Issue by sp0ok3r** [tobiasfrck/favorites_filter#2]
It would be cool, to export all the likes to file like csv, a table with all the sort options

**Comment by tobiasfrck** [comment]
Interesting idea! Can you elaborate what that would look like?
There is only so much info I can extract from the favorites page alone like: Link to item, title, brand, size, price, member and availability.
And all items that I can export need to be loaded ahead of time.
Is that enough to be useful?

**Comment by tobiasfrck** [comment]
Thank you for the nice mockup of your idea. While this is interesting and definitely something I could learn from, I don't know if I want to spend my time on such a feature. I can make a simple csv-export button, that would extract all the attributes mentioned in my previous reply, but that is probably not the exact feature you are looking for.
I am however open to pull requests if you want to make this feature happen :)

**Comment by tobiasfrck** [comment]
Sorry for the ping. I just want to close this issue for now. You or someone else can still open up a pull-request to implement this feature.
